### ISSUE TITLE
Server crash: NoSuchMethodError: org.apache.commons.lang3.mutable.MutableBoolean.setTrue()V

### ISSUE THREAD

**Issue by SkySem** [makamys/DMod#4]
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: org.apache.commons.lang3.mutable.MutableBoolean.setTrue()V
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.apache.commons.lang3.mutable.MutableBoolean.setTrue()V
	at makamys.dmod.lib.makamys.mclib.sloppydeploader.SloppyDepLoader.preInit(SloppyDepLoader.java:472)
	at makamys.dmod.lib.makamys.mclib.updatechecklibhelper.UpdateCheckLibHelper.preInit(UpdateCheckLibHelper.java:30)
	at makamys.dmod.DMod.preInit(DMod.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 5 more

**Comment by makamys** [comment]
It looks like there's something wrong with your version of the Apache Commons Lang library (my guess is its version is lower than 3.3). I can see two ways this could happen:
1. You have a wrong version of the library on your classpath. The classpath is written at the beginning of `fml-client-latest.log` like this:
`[main/DEBUG] [FML/]: Java classpath at launch is ...`
In my case there's `commons-lang3-3.3.2.jar` there. Is it the same for you?
2. Some mod has a different version of the library embedded inside it. If this was the case, that mod would have an `org/apache/commons/lang3` folder inside the jar. I'm not sure if this can actually happen though, I think the above library jar would override it if this happened.

**Comment by SkySem** [comment]
Yes, almost worked! I could not install it on the server (in the correct version) but thanks for the help

**Comment by makamys** [comment]
I'm not sure how you managed to get a version lower than 3.3.2, Forge should install that version automatically.
From my `forge-1.7.10-10.13.4.1614-1.7.10-installer.jar.log`:
```
MESSAGE: Considering library org.apache.commons:commons-lang3:3.3.2
MESSAGE: Downloading library org.apache.commons:commons-lang3:3.3.2
MESSAGE:   Trying unpacked library org.apache.commons:commons-lang3:3.3.2
```
